<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo">
    </a>
</p>

# **Hands-on Lab: Interactive Visual Analytics with Folium**

Estimated time needed: **40** minutes

The launch success rate may depend on many factors such as payload mass, orbit type, and so on. It may also depend on the location and proximities of a launch site, i.e., the initial position of rocket trajectories. Finding an optimal location for building a launch site certainly involves many factors and hopefully we could discover some of the factors by analyzing the existing launch site locations.

In the previous exploratory data analysis labs, you have visualized the SpaceX launch dataset using `matplotlib` and `seaborn` and discovered some preliminary correlations between the launch site and success rates. In this lab, you will be performing more interactive visual analytics using `Folium`.

## Objectives

This lab contains the following tasks:

*   **TASK 1:** Mark all launch sites on a map
*   **TASK 2:** Mark the success/failed launches for each site on the map
*   **TASK 3:** Calculate the distances between a launch site to its proximities

After completed the above tasks, you should be able to find some geographical patterns about launch sites.

Let's first import required Python packages for this lab:

In [4]:
import piplite
await piplite.install(['folium'])
await piplite.install(['pandas'])

In [5]:
import folium
import pandas as pd

In [6]:
from folium.plugins import MarkerCluster
from folium.plugins import MousePosition
from folium.features import DivIcon

If you need to refresh your memory about folium, you may download and refer to this previous folium lab:

[Generating Maps with Python](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DV0101EN-SkillsNetwork/labs/v4/DV0101EN-Exercise-Generating-Maps-in-Python.ipynb)

In [7]:
launch_sites = {
    'CCAFS LC-40': [28.562302, -80.577356],
    'CCAFS SLC-40': [28.563197, -80.576820],
    'KSC LC-39A': [28.573255, -80.646895],
    'VAFB SLC-4E': [34.632834, -120.610745]
}

map_center = [sum([loc[0] for loc in launch_sites.values()]) / len(launch_sites),
              sum([loc[1] for loc in launch_sites.values()]) / len(launch_sites)]

site_map = folium.Map(location=map_center, zoom_start=5)

for site, coords in launch_sites.items():
    folium.Marker(location=coords, popup=site).add_to(site_map)
site_map

First, let's try to add each site's location on a map using site's latitude and longitude coordinates

The following dataset with the name `spacex_launch_geo.csv` is an augmented dataset with latitude and longitude added for each site.

In [8]:
from js import fetch
import io

URL = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/spacex_launch_geo.csv'
resp = await fetch(URL)
spacex_csv_file = io.BytesIO((await resp.arrayBuffer()).to_py())
spacex_df=pd.read_csv(spacex_csv_file)

Now, you can take a look at what are the coordinates for each site.

In [9]:
spacex_df = spacex_df[['Launch Site', 'Lat', 'Long', 'class']]
launch_sites_df = spacex_df.groupby(['Launch Site'], as_index=False).first()
launch_sites_df = launch_sites_df[['Launch Site', 'Lat', 'Long']]
launch_sites_df

    Launch Site        Lat        Long
0   CCAFS LC-40  28.562302  -80.577356
1  CCAFS SLC-40  28.563197  -80.576820
2    KSC LC-39A  28.573255  -80.646895
3   VAFB SLC-4E  34.632834 -120.610745

Above coordinates are just plain numbers that can not give you any intuitive insights about where are those launch sites. If you are very good at geography, you can interpret those numbers directly in your mind. If not, that's fine too. Let's visualize those locations by pinning them on a map.

We first need to create a folium `Map` object, with an initial center location to be NASA Johnson Space Center at Houston, Texas.

In [10]:
nasa_coordinate = [29.559684888503615, -95.0830971930759]
site_map = folium.Map(location=nasa_coordinate, zoom_start=10)

We could use `folium.Circle` to add a highlighted circle area with a text label on a specific coordinate. For example,

In [11]:
circle = folium.Circle(nasa_coordinate, radius=1000, color='#d35400', fill=True).add_child(folium.Popup('NASA Johnson Space Center'))

marker = folium.map.Marker(
    nasa_coordinate,
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'NASA JSC',
        )
    )
site_map.add_child(circle)
site_map.add_child(marker)

and you should find a small yellow circle near the city of Houston and you can zoom-in to see a larger circle.

Now, let's add a circle for each launch site in data frame `launch_sites`

*TODO:*  Create and add `folium.Circle` and `folium.Marker` for each launch site on the site map

An example of folium.Circle:

`folium.Circle(coordinate, radius=1000, color='#000000', fill=True).add_child(folium.Popup(...))`

An example of folium.Marker:

`folium.map.Marker(coordinate, icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'label', ))`

In [12]:
site_map = folium.Map(location=nasa_coordinate, zoom_start=5)

for site_name, coords in launch_sites.items():
    folium.Circle(
        location=coords,
        radius=5000,  
        color='blue',
        fill=True,
        fill_color='cyan',
        fill_opacity=0.6,
        popup=site_name
    ).add_to(site_map)
site_map

The generated map with marked launch sites should look similar to the following:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_markers.png">
</center>

In [13]:
nasa_coordinate = [28.5623, -80.5774]

launch_sites = {
    'CCAFS LC-40': [28.562302, -80.577356],
    'CCAFS SLC-40': [28.563197, -80.576820],
    'KSC LC-39A': [28.573255, -80.646895],
    'VAFB SLC-4E': [34.632834, -120.610745]
}

map_center = [sum([loc[0] for loc in launch_sites.values()]) / len(launch_sites),
              sum([loc[1] for loc in launch_sites.values()]) / len(launch_sites)]

for site, coords in launch_sites.items():
    folium.Marker(location=coords, popup=site).add_to(site_map)

site_map = folium.Map(location=nasa_coordinate, zoom_start=5)

circle = folium.Circle(nasa_coordinate, radius=1000, color='#d35400', fill=True).add_child(folium.Popup('NASA Johnson Space Center'))
marker = folium.map.Marker(
    nasa_coordinate,
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'NASA JSC',
        )
    )
site_map.add_child(circle)
site_map.add_child(marker)

for site_name, coords in launch_sites.items():
    folium.Circle(
        location=coords,
        radius=5000,
        color='blue',
        fill=True,
        fill_color='cyan',
        fill_opacity=0.6,
        popup=site_name
    ).add_to(site_map)

site_map
site_map.save('launch_sites_maps.html')

In [14]:
site_map

Now, you can explore the map by zoom-in/out the marked areas
, and try to answer the following questions:

*   Are all launch sites in proximity to the Equator line?
*   Are all launch sites in very close proximity to the coast?

Also please try to explain your findings.

In [15]:
launch_sites = {
    'CCAFS LC-40': [28.562302, -80.577356],
    'CCAFS SLC-40': [28.563197, -80.576820],
    'KSC LC-39A': [28.573255, -80.646895],
    'VAFB SLC-4E': [34.632834, -120.610745]
}

map_center = [sum([loc[0] for loc in launch_sites.values()]) / len(launch_sites),
              sum([loc[1] for loc in launch_sites.values()]) / len(launch_sites)]

launch_success = spacex_df.set_index("Launch Site")["class"].to_dict()

site_map = folium.Map(location=map_center, zoom_start=5)

for site, coords in launch_sites.items():
    color = 'green' if launch_success.get(site, False) else 'red'
    folium.CircleMarker(
        location=coords,
        radius=10,
        color=color,
        fill=True,
        fill_color=color,
        fill_opacity=0.7,
        popup=f"{site} - {'Success' if launch_success.get(site) else 'Failed'}"
    ).add_to(site_map)

site_map

In [16]:
spacex_df.set_index("Launch Site")["class"].to_dict()

{'CCAFS LC-40': 1, 'VAFB SLC-4E': 0, 'KSC LC-39A': 1, 'CCAFS SLC-40': 0}

Next, let's try to enhance the map by adding the launch outcomes for each site, and see which sites have high success rates.
Recall that data frame spacex_df has detailed launch records, and the `class` column indicates if this launch was successful or not

In [17]:
spacex_df.tail(10)

     Launch Site        Lat       Long  class
46    KSC LC-39A  28.573255 -80.646895      1
47    KSC LC-39A  28.573255 -80.646895      1
48    KSC LC-39A  28.573255 -80.646895      1
49  CCAFS SLC-40  28.563197 -80.576820      1
50  CCAFS SLC-40  28.563197 -80.576820      1
51  CCAFS SLC-40  28.563197 -80.576820      0
52  CCAFS SLC-40  28.563197 -80.576820      0
53  CCAFS SLC-40  28.563197 -80.576820      0
54  CCAFS SLC-40  28.563197 -80.576820      1
55  CCAFS SLC-40  28.563197 -80.576820      0

Next, let's create markers for all launch records.
If a launch was successful `(class=1)`, then we use a green marker and if a launch was failed, we use a red marker `(class=0)`

Note that a launch only happens in one of the four launch sites, which means many launch records will have the exact same coordinate. Marker clusters can be a good way to simplify a map containing many markers having the same coordinate.

Let's first create a `MarkerCluster` object

In [18]:
marker_cluster = MarkerCluster()

*TODO:* Create a new column in `spacex_df` dataframe called `marker_color` to store the marker colors based on the `class` value

In [19]:
spacex_df['marker_color'] = spacex_df['class'].apply(lambda x: 'green' if x == 1 else 'red')

*TODO:* For each launch result in `spacex_df` data frame, add a `folium.Marker` to `marker_cluster`

In [20]:
site_map.add_child(marker_cluster)

for idx, row in spacex_df.iterrows():
    marker = folium.Marker(
        location=[row['Lat'], row['Long']],
        popup=f"Site: {row['Launch Site']}<br>Class: {row['class']}",
        icon=folium.Icon(color=row['marker_color'])
    )
    marker.add_to(marker_cluster)


site_map

Your updated map may look like the following screenshots:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_cluster.png">
</center>

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_cluster_zoomed.png">
</center>

From the color-labeled markers in marker clusters, you should be able to easily identify which launch sites have relatively high success rates.

In [21]:
import math


def haversine(lat1, lon1, lat2, lon2):
    R = 6371  # Earth radius in kilometers
    phi1 = math.radians(lat1)
    phi2 = math.radians(lat2)
    delta_phi = math.radians(lat2 - lat1)
    delta_lambda = math.radians(lon2 - lon1)
    
    a = math.sin(delta_phi / 2) ** 2 + \
        math.cos(phi1) * math.cos(phi2) * math.sin(delta_lambda / 2) ** 2
    
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    
    return R * c

launch_sites = {
    'CCAFS LC-40': [28.562302, -80.577356],
    'CCAFS SLC-40': [28.563197, -80.576820],
    'KSC LC-39A': [28.573255, -80.646895],
    'VAFB SLC-4E': [34.632834, -120.610745]
}

distances = {}

for site1, coord1 in launch_sites.items():
    distances[site1] = {}
    for site2, coord2 in launch_sites.items():
        if site1 != site2:
            dist = haversine(coord1[0], coord1[1], coord2[0], coord2[1])
            distances[site1][site2] = round(dist, 2)

for site, proximities in distances.items():
    print(f"Distances from {site}:")
    for prox_site, dist_km in proximities.items():
        print(f"  to {prox_site}: {dist_km} km")
    print()

Distances from CCAFS LC-40:
  to CCAFS SLC-40: 0.11 km
  to KSC LC-39A: 6.9 km
  to VAFB SLC-4E: 3825.84 km

Distances from CCAFS SLC-40:
  to CCAFS LC-40: 0.11 km
  to KSC LC-39A: 6.93 km
  to VAFB SLC-4E: 3825.85 km

Distances from KSC LC-39A:
  to CCAFS LC-40: 6.9 km
  to CCAFS SLC-40: 6.93 km
  to VAFB SLC-4E: 3819.05 km

Distances from VAFB SLC-4E:
  to CCAFS LC-40: 3825.84 km
  to CCAFS SLC-40: 3825.85 km
  to KSC LC-39A: 3819.05 km

Next, we need to explore and analyze the proximities of launch sites.

Let's first add a `MousePosition` on the map to get coordinate for a mouse over a point on the map. As such, while you are exploring the map, you can easily find the coordinates of any points of interests (such as railway)

In [22]:
formatter = "function(num) {return L.Util.formatNum(num, 5);};"
mouse_position = MousePosition(
    position='topright',
    separator=' Long: ',
    empty_string='NaN',
    lng_first=False,
    num_digits=20,
    prefix='Lat:',
    lat_formatter=formatter,
    lng_formatter=formatter,
)

site_map.add_child(mouse_position)
site_map

Now zoom in to a launch site and explore its proximity to see if you can easily find any railway, highway, coastline, etc. Move your mouse to these points and mark down their coordinates (shown on the top-left) in order to the distance to the launch site.

Now zoom in to a launch site and explore its proximity to see if you can easily find any railway, highway, coastline, etc. Move your mouse to these points and mark down their coordinates (shown on the top-left) in order to the distance to the launch site.

In [23]:
from math import sin, cos, sqrt, atan2, radians

def calculate_distance(lat1, lon1, lat2, lon2):
    R = 6373.0

    lat1 = radians(lat1)
    lon1 = radians(lon1)
    lat2 = radians(lat2)
    lon2 = radians(lon2)

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    distance = R * c
    return distance

*TODO:* Mark down a point on the closest coastline using MousePosition and calculate the distance between the coastline point and the launch site.

In [24]:
coastline_points = [
    [28.56367, -80.57163],
    [28.57000, -80.58000],
    [28.55500, -80.59000]
]
def haversine(lat1, lon1, lat2, lon2):
    R = 6371  
    phi1, phi2 = math.radians(lat1), math.radians(lat2)
    d_phi = math.radians(lat2 - lat1)
    d_lambda = math.radians(lon2 - lon1)

    a = math.sin(d_phi / 2) ** 2 + math.cos(phi1) * math.cos(phi2) * math.sin(d_lambda / 2) ** 2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    return R * c

def find_closest_coastline(launch_lat, launch_lon, coastline_points):
    min_distance = float('inf')
    closest_point = None
    for point in coastline_points:
        dist = haversine(launch_lat, launch_lon, point[0], point[1])
        if dist < min_distance:
            min_distance = dist
            closest_point = point
    return closest_point, min_distance
launch_site = [28.562302, -80.577356]

closest_coast, distance_km = find_closest_coastline(launch_site[0], launch_site[1], coastline_points)

print(f"Closest coastline point: {closest_coast}")
print(f"Distance to coastline: {distance_km:.3f} km")

map_center = [(launch_site[0] + closest_coast[0]) / 2, (launch_site[1] + closest_coast[1]) / 2]
site_map = folium.Map(location=map_center, zoom_start=13)

folium.Marker(location=launch_site, popup='Launch Site', icon=folium.Icon(color='blue')).add_to(site_map)

folium.Marker(location=closest_coast, popup=f'Closest Coastline\nDistance: {distance_km:.3f} km', icon=folium.Icon(color='green')).add_to(site_map)

folium.PolyLine(locations=[launch_site, closest_coast], color='red').add_to(site_map)

site_map

Closest coastline point: [28.56367, -80.57163]
Distance to coastline: 0.580 km

*TODO:* Draw a `PolyLine` between a launch site to the selected coastline point

In [26]:
launch_site = [28.562302, -80.577356]
closest_coastline = [28.56367, -80.57163]

map_center = [(launch_site[0] + closest_coastline[0]) / 2, (launch_site[1] + closest_coastline[1]) / 2]
site_map = folium.Map(location=map_center, zoom_start=13)

folium.Marker(location=launch_site, popup='Launch Site').add_to(site_map)
folium.Marker(location=closest_coastline, popup='Closest Coastline').add_to(site_map)

lines = folium.PolyLine(locations=[launch_site, closest_coastline], weight=2, color='blue')

site_map.add_child(lines)

site_map.save('launch_site_coastline_map.html')
site_map

Your updated map with distance line should look like the following screenshot:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_distance.png">
</center>

*TODO:* Similarly, you can draw a line betwee a launch site to its closest city, railway, highway, etc. You need to use `MousePosition` to find the their coordinates on the map first

A railway map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/railway.png">
</center>

A highway map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/highway.png">
</center>

A city map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/city.png">
</center>

In [27]:
closest_city = [28.56789, -80.58012]
closest_railway = [28.55900, -80.57500]
closest_highway = [28.56000, -80.57000]

folium.Marker(location=closest_city, popup='Closest City', icon=folium.Icon(color='green')).add_to(site_map)
folium.Marker(location=closest_railway, popup='Closest Railway', icon=folium.Icon(color='orange')).add_to(site_map)
folium.Marker(location=closest_highway, popup='Closest Highway', icon=folium.Icon(color='purple')).add_to(site_map)

folium.PolyLine(locations=[launch_site, closest_city], color='green', weight=2).add_to(site_map)
folium.PolyLine(locations=[launch_site, closest_railway], color='orange', weight=2).add_to(site_map)
folium.PolyLine(locations=[launch_site, closest_highway], color='purple', weight=2).add_to(site_map)

site_map.save('launch_site_proximities_map.html')
site_map

After you plot distance lines to the proximities, you can answer the following questions easily:

*   Are launch sites in close proximity to railways?
*   Are launch sites in close proximity to highways?
*   Are launch sites in close proximity to coastline?
*   Do launch sites keep certain distance away from cities?

Also please try to explain your findings.

# Next Steps:

Now you have discovered many interesting insights related to the launch sites' location using folium, in a very interactive way. Next, you will need to build a dashboard using Ploty Dash on detailed launch records.

## Authors

[Pratiksha Verma](https://www.linkedin.com/in/pratiksha-verma-6487561b1/)

<!--## Change Log--!>

<!--| Date (YYYY-MM-DD) | Version | Changed By      | Change Description      |
| ----------------- | ------- | -------------   | ----------------------- |
| 2022-11-09        | 1.0     | Pratiksha Verma | Converted initial version to Jupyterlite|--!>

### <h3 align="center"> IBM Corporation 2022. All rights reserved. <h3/>